# Generated by Django 3.2.13 on 2022-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentgroup_students_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, choices=[('Petrenko', 'Петренко'), ('Ivanenko', 'Іваненко')], max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
